### PR TITLE
fixes #33

### LINKED ISSUE #33: Nested pipelines report invalid times
From a trace:

```
[TRAC] 1c7de31dfc server.Init                    S=0 Tot=0.0003 %=44.39
[TRAC] 1c7de31dfc *auth_filter.Filter            S=0 Tot=0.0002 %=39.46
[TRAC] 1c7de31dfc *falcore.Pipeline              S=0 Tot=-8143286784.0000 %=-1384912741466112.00
...

```

### PR DESCRIPTION
**Pull request by dgrijalva**
Fixes #33.

Leaves pipelines out of traces.  All pipeline time is included in "Overhead".

### CODE REVIEW

**Comment by smw1218** [comment]
Is there a reason why can't we appropriately fill in the stats for this case?  Running another pipeline does not seem like Overhead to me :)

**Comment by dgrijalva** [comment]
1) pipelines just execute things from a list.  they take no time.
2) the root pipeline has always been in "overhead" as they're not explicitly tracked.
3) we probably could, but it would require more tracking and overhead than it's worth
4) I'd like to see you try

6) profit

**Comment by smw1218** [comment]
oh... so the filter stages run inside the pipeline are broken out appropriately?

**Comment by dgrijalva** [comment]
Correct.

**Pull request merged**
