### PR TITLE
A new Request struct field which provides a container to store values for a request

### PR DESCRIPTION
**Pull request by amir**
A new unexported field (context), with four new funcs (Get, Set, Delete, Clear) to interact with it.
This provides a mechanism to store values for a given request, and use it later, down in the pipeline.

### CODE REVIEW

**Comment by dgrijalva** [comment]
What's the advantage of this approach over just adding `Context map[interface{}]interface{}` to the request.

We've talked back and forth about adding this.  It's not in there now because we haven't figured the best way to do it.  Can you share your use case for this?

**Comment by amir** [comment]
No advantage over `Context map[interface{}]interface{}`, IMHO it is just cleaner.

I am not sure if I grokked falcore, but here's an example:

``` go
pipeline := falcore.NewPipeline()
pipeline.Upstream.PushBack(authorizationFilter)

var apiVersionOne apiFilter
router := falcore.NewPathRouter()
router.AddMatch("^/1/", apiVersionOne)
pipeline.Upstream.PushBack(router)
```

``` go
var authorizationFilter = falcore.NewRequestFilter(func(req *falcore.Request) *http.Response {
    username, password, err := basicAuthorization(req.HttpRequest)
    if err != nil {
        return falcore.SimpleResponse(req.HttpRequest, 401, nil, "Unauthorized")
    }
    user, err := dbSession.Authenticate(username, password)
    if err != nil {
        return falcore.SimpleResponse(req.HttpRequest, 401, nil, "Unauthorized")
    }
    req.Set("user", user)
})
```

``` go
func (f apiFilter) FilterRequest(req *falcore.Request) (result *http.Response) {
    user := req.Get("user").(models.User)
    dbSession.doSomething(user.Email)
}
```

**Comment by smw1218** [comment]
I think you've grokked falcore perfectly and I agree that this feature would be very useful in many situations.

I like what you've done here with the interface. I think the advantage over exposing the struct object is the lazy initialization.  I definitely don't want to be calling make for the map every request if it's never used.  Pushing init to the user doesn't seem as clean to me if we just expose the struct object directly.
The only thing missing is access to the keys which I think is necessary if multiple pipeline stages are pushing disparate data into the context.

Here is what I think of the alternatives that I can think of:
0. Pull request as-is
  .- Non-standard interface to a basic type
  .- Missing access to range/keys
  .+ Lazy init done by falcore
1. exposed Context map[interface{}]interface{}
  .- Pushing init to the user seems sloppy
  .- Always initing it in the constructor seems inefficient (memory and time).
  .+ Direct access to the standard map interface (allowing direct range operators)
2. Context map[string]interface{} (exposed or not)
  .- Slightly less generic but by far the most common use case.  
  .+ Once keys are exposed, this would be less type conversion code

I'm leaning toward 0 with closure access directly to the map like:

func (r *Request) WithContext(cb func(context map[interface{}]interface{}) ) {
   // lazy init ...
   cb(r.context)
}

What do you guys think?

**Comment by dgrijalva** [comment]
That just seems like more complexity.  Why don't we just initialize a map[string]interface{} for each request and expose it?  Allocating one empty map is not going to hurt our performance.  They could be re-used if we're really concerned.

My bigger concern is collision between various filters.

**Comment by amir** [comment]
Thanks Scott for putting all the alternatives with pros, and cons. Looking at your list, I'm now more leaning toward `2`.

Regarding `1`, if user is supposed to init it manually, then why not

``` go
type Context struct {
    lock sync.Mutex
    storage map[*falcore.Request]map[interface{}]interface{}
}
func (c *Context) Get(req *falcore.Request, key, val interface{}) {
    c.lock.Lock()
    defer c.lock.Unlock()
    if c.storage != nil && c.storage[req] != nil {
        return c.storage[req][key]
    }
    return nil
}
// and the rest of functions
```

This way no change is needed to happen in falcore. I mean if falcore is not going to add any method, or initialize anything for the user, and the only thing that is going to do, is adding an uninitialized map to it's Request struct, then why bother? User could do it with a custom locker with key being the current request.

**Comment by dgrijalva** [comment]
Keep in mind that an application is likely to utilize both filters they built themselves and filters they pulled in from elsewhere (other internal projects or open source).  Whatever we present as context needs to be consistent and managed by falcore lest we have pandemonium.

Callbacks feel heavy to me just to avoid creating a few unused maps.  I'd be interested in a performance comparison between the two worst case scenarios: 
1) we autoalloc the map and it's never used
2) we require callbacks and they're used multiple times per request

I suspect the creation of closures will prove more the expensive, but it's worth testing.

**Comment by smw1218** [comment]
Re amir: Having the map in the falcore request is very helpful because the whole design is trying to enable reusable components.  If you create some auth info filter and share it on github, maybe others can plug it directly into their app without creating a custom (and global) locker.

Re dgrijalva: I was proposing the addition of the callback to the current pull request so it would be used only in cases where direct access to the whole map or keys was required.  I think the Get's and Set's would be more commonly used.

If you don't think the make on every request would be a big deal, then I'm willing to drop it in without testing.  I know it's on the order of a few microseconds.

What does everyone think about: Context map[string]interface{} with public access, initialized by the constructor?

**Comment by dgrijalva** [comment]
These are probably too simplistic to be meaningful, but at the very least it demonstrates the cost of either of these options is negligible.

``` go
package main

func main(){
    for i := 0; i < 10000000; i++ {
        foo := make(map[string]interface{})
        _ = foo
    }
}
```

``` go
package main

func main(){
    a := "foo"
    b := "bar"
    for i := 0; i < 10000000; i++ {
        c := func(){
            _ = a
            _ = b
        }

        c()
    }
}
```

```

Daves-MacBook-Air:Desktop dgrijalva$ time ./closure

real    0m3.332s
user    0m3.320s
sys 0m0.009s
```

``` go

Daves-MacBook-Air:Desktop dgrijalva$ time ./map

real    0m3.393s
user    0m3.379s
sys 0m0.012s
```

**Comment by dgrijalva** [comment]
scott: sounds like a plan to me.

Is it possible/worth it to reuse these?

**Comment by smw1218** [comment]
not worth the code for reuse.  what does everyone think about:

https://github.com/ngmoco/falcore/pull/22

**Comment by amir** [comment]
Just one last thing. Current pull request's Get functionality could have been further developed to provide the possibility of returning a default value if desired key does not exist. But since Go does not support method overloading, that means another func needs to be added.

**Comment by dgrijalva** [comment]
amir: that would require pushing application logic into falcore or adding yet more methods for managing context.

If you want default values, just make a filter that sets defaults and put it in the front of your pipeline.

**Comment by smw1218** [comment]
Default values tend to be application specific, and I rarely use this feature in languages where it is an option for maps.

An alternative solution would be to add a RequestFilter to set any reasonable defaults in the Context at the start of your pipeline.

Handling nils for arbitrary missing keys seems like a minor burden and good coding practice. I have found that hiding missing values behind a default problematic in practice.  Especially when it's setup in some other file or a third-party plugin changes the default.

**Pull request closed without merging**
